export enum ContactTypeDescription {
  Home = 'Home',
  Business = 'Business',
  Cell = 'Cell',
  Email = 'E-mail',
  Business2 = 'Business Phone 2',
  BusinessFax = 'Business Fax',
  Pager = 'Pager',
  Pay = 'Pay',
  Fax = 'Fax',
  WebAddress = 'Web Address',
  Vacation = 'Vacation Phone',
  NursingHome = 'Nursing Home Phone',
  Emergency1 = 'Emergency Phone 1',
  Emergency2 = 'Emergency Phone 2',
  Emergency3 = 'Emergency Phone 3',
  Emergency4 = 'Emergency Phone 4',
  TTY = 'TTY',
  NapisContact1 = 'Napis Contact 1',
  NapisContact2 = 'Napis Contact 2'
}
